### ISSUE TITLE
Amazon IAP exception on taskcompletionsource

### ISSUE THREAD

**Issue by EmilAlipiev** [TobiasBuchholz/PlayGround#1]
I saw your stackoverflow question. i am having the same problem as System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
I checked your code and we have similar implementation. I am wondering have you found any solution for that? 

it looks like that it throws exception within the library but what causes this i am not sure.

07-26 18:35:04.628 E/mono-rt (24900): [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
07-26 18:35:04.628 E/mono-rt (24900):   at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
07-26 18:35:04.628 E/mono-rt (24900):   at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
07-26 18:35:04.628 E/mono-rt (24900):   at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
07-26 18:35:04.628 E/mono-rt (24900):   at com.amazon.device.iap.cpt.AmazonIapV2Impl.FireEvent (System.String jsonMessage) [0x000b6] in <909e8c2781f24da69e9ca12b0195ac21>:0

**Comment by TobiasBuchholz** [comment]
No, unfortunately not, I sticked to the hacky workaround I've mentioned in my second hint in that stackoverflow question.

**Comment by EmilAlipiev** [comment]
for me it throws always exception on the line  ` taskCompletionSource.SetResult(result); ` for PurchaseUpdates functions. even if I use your hacky solution but for other functions works fine.
 if i use instead this line `var sucess = taskCompletionSource.TrySetResult(result); `
it actually works fine

**Comment by EmilAlipiev** [comment]
You are actually right, it also throws exception on the line   `context.RemoveGetProductDataResponseListener(delegator.responseDelegate);` and your hacky solution fix it. it looks like problem is in the library. 

may I ask where did you see this ResponseDelegator and TaskCompletionSource? or you figured out yourself. I cant seem to find a lot of information about Amazon Iap. Some Android samples are programmed differently by creating a new Activity and returning data from that activity but I couldnt achieve this solution.

**Comment by EmilAlipiev** [comment]
I think that your hacky solution is actually correct solution. it just has to be async operation. using like below is a solution as well. I also replied you on SO.
```

PurchaseResponseDelegator delegator = null;
                    delegator = new PurchaseResponseDelegator(async response =>
                    {
                        await Task.Run(() =>
                        {
                            if (response.RequestId == requestId)
                            {
                                var result = GetPurchaseEventHandler(response);
                                var sucess = taskCompletionSource.TrySetResult(result);
                                 
                                context.RemovePurchaseResponseListener(delegator.responseDelegate);
                            }
                        } );
                    });
                    // Register for an event
                    context.AddPurchaseResponseListener(delegator.respons
```eDelegate);
